# Copyright Takeshi Yonezu. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'

services:

  node1:
    image: arm32v7/${IROHA_IMG}
    ports:
      - "50051:50051"
    environment:
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - .:/opt/iroha/config
      - ./block_store1:/tmp/block_store
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    command: >
      bash -c "sleep 20;
      /opt/iroha/bin/irohad --config config/iroha1.conf
      --genesis_block config/genesis.block
      --keypair_name config/node1"
    depends_on:
      - postgres1

  node2:
    image: arm32v7/${IROHA_IMG}
    environment:
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - .:/opt/iroha/config
      - ./block_store2:/tmp/block_store
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    command: >
      bash -c "sleep 20;
      /opt/iroha/bin/irohad --config config/iroha2.conf
      --genesis_block config/genesis.block
      --keypair_name config/node2"
    depends_on:
      - postgres2

  node3:
    image: arm32v7/${IROHA_IMG}
    environment:
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - .:/opt/iroha/config
      - ./block_store3:/tmp/block_store
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    command: >
      bash -c "sleep 20;
      /opt/iroha/bin/irohad --config config/iroha3.conf
      --genesis_block config/genesis.block
      --keypair_name config/node3"
    depends_on:
      - postgres3

  node4:
    image: arm32v7/${IROHA_IMG}
    environment:
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - .:/opt/iroha/config
      - ./block_store4:/tmp/block_store
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    command: >
      bash -c "sleep 20;
      /opt/iroha/bin/irohad --config config/iroha4.conf
      --genesis_block config/genesis.block
      --keypair_name config/node4"
    depends_on:
      - postgres4

  postgres1:
    image: arm32v7/postgres:9.5
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld
    depends_on:
      - redis1

  postgres2:
    image: arm32v7/postgres:9.5
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld
    depends_on:
      - redis2

  postgres3:
    image: arm32v7/postgres:9.5
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld
    depends_on:
      - redis3

  postgres4:
    image: arm32v7/postgres:9.5
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld
    depends_on:
      - redis4

  redis1:
    image: arm32v7/redis

  redis2:
    image: arm32v7/redis
    depends_on:
      - redis1
      - postgres1
      - node1

  redis3:
    image: arm32v7/redis
    depends_on:
      - node2

  redis4:
    image: arm32v7/redis
    depends_on:
      - node3

volumes:
  ccache-data:
